### ISSUE TITLE
进阶流体钻机引发崩溃

### ISSUE THREAD

**Issue by joe1166** [nutant233/GregTech-Leisure#47]
自从在服务器中放置了一台进阶流体钻机后，每次启动时100%崩溃并报错，第二次启动有概率成功启动并正常游玩，但是最近突然就彻底启动不了。报错信息都是显示各个流体钻机，但在单人档里逐个检查后没有发现异样。

每次崩溃报错都包含流体钻机，但每次引发崩溃的不是同一台，且有时候崩溃日志里的坐标处并没有流体钻机
日志：https://mclo.gs/o53z5Iz

`Time: 2024-08-17 17:31:43
Description: Ticking block entity

java.lang.NullPointerException: Cannot invoke "com.gregtechceu.gtceu.api.recipe.GTRecipeType.getChanceFunction()" because the return value of "com.gregtechceu.gtceu.api.recipe.GTRecipe.getType()" is null
	at com.gregtechceu.gtceu.api.recipe.RecipeRunner.fillContent(RecipeRunner.java:86) ~[gtceu-1.20.1-1.3.1.jar%23257!/:?] {re:classloading}
	at com.gregtechceu.gtceu.api.recipe.RecipeRunner.handle(RecipeRunner.java:65) ~[gtceu-1.20.1-1.3.1.jar%23257!/:?] {re:classloading}
	at com.gregtechceu.gtceu.api.recipe.GTRecipe.matchRecipeContents(GTRecipe.java:218) ~[gtceu-1.20.1-1.3.1.jar%23257!/:?] {re:mixin,re:classloading}
	at com.gregtechceu.gtceu.api.recipe.GTRecipe.matchRecipe(GTRecipe.java:204) ~[gtceu-1.20.1-1.3.1.jar%23257!/:?] {re:mixin,re:classloading}
	at com.gregtechceu.gtceu.api.recipe.GTRecipe.matchTickRecipe(GTRecipe.java:198) ~[gtceu-1.20.1-1.3.1.jar%23257!/:?] {re:mixin,re:classloading}
	at com.gregtechceu.gtceu.api.machine.trait.RecipeLogic.handleTickRecipe(RecipeLogic.java:339) ~[gtceu-1.20.1-1.3.1.jar%23257!/:?] {re:classloading}
	at com.gregtechceu.gtceu.api.machine.trait.RecipeLogic.handleRecipeWorking(RecipeLogic.java:242) ~[gtceu-1.20.1-1.3.1.jar%23257!/:?] {re:classloading}
	at com.gregtechceu.gtceu.api.machine.trait.RecipeLogic.serverTick(RecipeLogic.java:182) ~[gtceu-1.20.1-1.3.1.jar%23257!/:?] {re:classloading}
	at com.gregtechceu.gtceu.api.machine.TickableSubscription.run(TickableSubscription.java:23) ~[gtceu-1.20.1-1.3.1.jar%23257!/:?] {re:classloading}
	at com.gregtechceu.gtceu.api.machine.MetaMachine.executeTick(MetaMachine.java:294) ~[gtceu-1.20.1-1.3.1.jar%23257!/:?] {re:classloading}
	at com.gregtechceu.gtceu.api.machine.MetaMachine.serverTick(MetaMachine.java:266) ~[gtceu-1.20.1-1.3.1.jar%23257!/:?] {re:classloading}
	at com.gregtechceu.gtceu.api.block.IMachineBlock.lambda$getTicker$0(IMachineBlock.java:66) ~[gtceu-1.20.1-1.3.1.jar%23257!/:?] {re:classloading}
	at net.minecraft.world.level.chunk.LevelChunk$BoundTickingBlockEntity.m_142224_(LevelChunk.java:689) ~[client-1.20.1-20230612.114412-srg.jar%23292!/:?] {re:mixin,re:classloading,pl:mixin:APP:lithium.mixins.json:world.block_entity_ticking.world_border.DirectBlockEntityTickInvokerMixin,pl:mixin:A}
	at net.minecraft.world.level.chunk.LevelChunk$RebindableTickingBlockEntityWrapper.m_142224_(LevelChunk.java:782) ~[client-1.20.1-20230612.114412-srg.jar%23292!/:?] {re:classloading}
	at net.minecraft.world.level.Level.redirect$bem000$observable$redirectTick(Level.java:1040) ~[client-1.20.1-20230612.114412-srg.jar%23292!/:?] {re:computing_frames,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.world.level.Level.m_46463_(Level.java:468) ~[client-1.20.1-20230612.114412-srg.jar%23292!/:?] {re:computing_frames,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:351) ~[client-1.20.1-20230612.114412-srg.jar%23292!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:libx:level_load,re:classloading,pl:accesstransformer:B,xf:fml:libx:level_load,pl:mixin:APP:modernfix-common.mixins.json:bugfix.chunk_deadlock.ServerLevelMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.faster_structure_location.ServerLevelMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.remove_spawn_chunks.ServerLevelMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.cache_strongholds.ServerLevelMixin,pl:mixin:APP:observable.common.json:ServerLevelMixin,pl:mixin:APP:lithium.mixins.json:alloc.chunk_random.ServerWorldMixin,pl:mixin:APP:lithium.mixins.json:chunk.entity_class_groups.ServerWorldAccessor,pl:mixin:APP:lithium.mixins.json:entity.inactive_navigations.ServerWorldMixin,pl:mixin:APP:lithium.mixins.json:profiler.ServerWorldMixin,pl:mixin:APP:lithium.mixins.json:util.entity_movement_tracking.ServerWorldAccessor,pl:mixin:APP:kubejs-common.mixins.json:ServerLevelMixin,pl:mixin:APP:adastra-common.mixins.json:common.ServerLevelMixin,pl:mixin:APP:adastra-common.mixins.json:common.multipart.ServerLevelMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:893) ~[client-1.20.1-20230612.114412-srg.jar%23292!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:814) ~[client-1.20.1-20230612.114412-srg.jar%23292!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:89) ~[client-1.20.1-20230612.114412-srg.jar%23292!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:modernfix-common.mixins.json:perf.thread_priorities.IntegratedServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:661) ~[client-1.20.1-20230612.114412-srg.jar%23292!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:251) ~[client-1.20.1-20230612.114412-srg.jar%23292!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at java.lang.Thread.run(Thread.java:1583) ~[?:?] {re:mixin}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Suspected Mods: 
	GregTech (gtceu), Version: 1.3.1
		at TRANSFORMER/gtceu@1.3.1/com.gregtechceu.gtceu.api.recipe.RecipeRunner.fillContent(RecipeRunner.java:86)

	Observable (observable), Version: 4.4.1
		Issue tracker URL: https://github.com/tasgon/observable/issues
		Mixin class: observable.mixin.LevelMixin
		Target: net.minecraft.world.level.Level
		at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.level.Level.redirect$bem000$observable$redirectTick(Level.java:1040)
Stacktrace:
	at com.gregtechceu.gtceu.api.recipe.RecipeRunner.fillContent(RecipeRunner.java:86) ~[gtceu-1.20.1-1.3.1.jar%23257!/:?] {re:classloading}
	at com.gregtechceu.gtceu.api.recipe.RecipeRunner.handle(RecipeRunner.java:65) ~[gtceu-1.20.1-1.3.1.jar%23257!/:?] {re:classloading}
	at com.gregtechceu.gtceu.api.recipe.GTRecipe.matchRecipeContents(GTRecipe.java:218) ~[gtceu-1.20.1-1.3.1.jar%23257!/:?] {re:mixin,re:classloading}
	at com.gregtechceu.gtceu.api.recipe.GTRecipe.matchRecipe(GTRecipe.java:204) ~[gtceu-1.20.1-1.3.1.jar%23257!/:?] {re:mixin,re:classloading}
	at com.gregtechceu.gtceu.api.recipe.GTRecipe.matchTickRecipe(GTRecipe.java:198) ~[gtceu-1.20.1-1.3.1.jar%23257!/:?] {re:mixin,re:classloading}
	at com.gregtechceu.gtceu.api.machine.trait.RecipeLogic.handleTickRecipe(RecipeLogic.java:339) ~[gtceu-1.20.1-1.3.1.jar%23257!/:?] {re:classloading}
	at com.gregtechceu.gtceu.api.machine.trait.RecipeLogic.handleRecipeWorking(RecipeLogic.java:242) ~[gtceu-1.20.1-1.3.1.jar%23257!/:?] {re:classloading}
	at com.gregtechceu.gtceu.api.machine.trait.RecipeLogic.serverTick(RecipeLogic.java:182) ~[gtceu-1.20.1-1.3.1.jar%23257!/:?] {re:classloading}
	at com.gregtechceu.gtceu.api.machine.TickableSubscription.run(TickableSubscription.java:23) ~[gtceu-1.20.1-1.3.1.jar%23257!/:?] {re:classloading}
	at com.gregtechceu.gtceu.api.machine.MetaMachine.executeTick(MetaMachine.java:294) ~[gtceu-1.20.1-1.3.1.jar%23257!/:?] {re:classloading}
	at com.gregtechceu.gtceu.api.machine.MetaMachine.serverTick(MetaMachine.java:266) ~[gtceu-1.20.1-1.3.1.jar%23257!/:?] {re:classloading}
	at com.gregtechceu.gtceu.api.block.IMachineBlock.lambda$getTicker$0(IMachineBlock.java:66) ~[gtceu-1.20.1-1.3.1.jar%23257!/:?] {re:classloading}
	at net.minecraft.world.level.chunk.LevelChunk$BoundTickingBlockEntity.m_142224_(LevelChunk.java:689) ~[client-1.20.1-20230612.114412-srg.jar%23292!/:?] {re:mixin,re:classloading,pl:mixin:APP:lithium.mixins.json:world.block_entity_ticking.world_border.DirectBlockEntityTickInvokerMixin,pl:mixin:A}
	at net.minecraft.world.level.chunk.LevelChunk$RebindableTickingBlockEntityWrapper.m_142224_(LevelChunk.java:782) ~[client-1.20.1-20230612.114412-srg.jar%23292!/:?] {re:classloading}
	at net.minecraft.world.level.Level.redirect$bem000$observable$redirectTick(Level.java:1040) ~[client-1.20.1-20230612.114412-srg.jar%23292!/:?] {re:computing_frames,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.world.level.Level.m_46463_(Level.java:468) ~[client-1.20.1-20230612.114412-srg.jar%23292!/:?] {re:computing_frames,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:351) ~[client-1.20.1-20230612.114412-srg.jar%23292!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:libx:level_load,re:classloading,pl:accesstransformer:B,xf:fml:libx:level_load,pl:mixin:APP:modernfix-common.mixins.json:bugfix.chunk_deadlock.ServerLevelMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.faster_structure_location.ServerLevelMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.remove_spawn_chunks.ServerLevelMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.cache_strongholds.ServerLevelMixin,pl:mixin:APP:observable.common.json:ServerLevelMixin,pl:mixin:APP:lithium.mixins.json:alloc.chunk_random.ServerWorldMixin,pl:mixin:APP:lithium.mixins.json:chunk.entity_class_groups.ServerWorldAccessor,pl:mixin:APP:lithium.mixins.json:entity.inactive_navigations.ServerWorldMixin,pl:mixin:APP:lithium.mixins.json:profiler.ServerWorldMixin,pl:mixin:APP:lithium.mixins.json:util.entity_movement_tracking.ServerWorldAccessor,pl:mixin:APP:kubejs-common.mixins.json:ServerLevelMixin,pl:mixin:APP:adastra-common.mixins.json:common.ServerLevelMixin,pl:mixin:APP:adastra-common.mixins.json:common.multipart.ServerLevelMixin,pl:mixin:A}
-- Block entity being ticked --
Details:
	Name: gtceu:mv_fluid_drilling_rig // com.gregtechceu.gtceu.api.blockentity.MetaMachineBlockEntity
	Block: Block{gtceu:mv_fluid_drilling_rig}[facing=north,server_tick=true,upwards_facing=north]
	Block location: World: (456,82,5), Section: (at 8,2,5 in 28,5,0; chunk contains blocks 448,-64,0 to 463,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Block: Block{gtceu:mv_fluid_drilling_rig}[facing=north,server_tick=true,upwards_facing=north]
	Block location: World: (456,82,5), Section: (at 8,2,5 in 28,5,0; chunk contains blocks 448,-64,0 to 463,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
Stacktrace:
	at net.minecraft.world.level.chunk.LevelChunk$BoundTickingBlockEntity.m_142224_(LevelChunk.java:689) ~[client-1.20.1-20230612.114412-srg.jar%23292!/:?] {re:mixin,re:classloading,pl:mixin:APP:lithium.mixins.json:world.block_entity_ticking.world_border.DirectBlockEntityTickInvokerMixin,pl:mixin:A}
	at net.minecraft.world.level.chunk.LevelChunk$RebindableTickingBlockEntityWrapper.m_142224_(LevelChunk.java:782) ~[client-1.20.1-20230612.114412-srg.jar%23292!/:?] {re:classloading}
	at net.minecraft.world.level.Level.redirect$bem000$observable$redirectTick(Level.java:1040) ~[client-1.20.1-20230612.114412-srg.jar%23292!/:?] {re:computing_frames,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.world.level.Level.m_46463_(Level.java:468) ~[client-1.20.1-20230612.114412-srg.jar%23292!/:?] {re:computing_frames,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:351) ~[client-1.20.1-20230612.114412-srg.jar%23292!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:libx:level_load,re:classloading,pl:accesstransformer:B,xf:fml:libx:level_load,pl:mixin:APP:modernfix-common.mixins.json:bugfix.chunk_deadlock.ServerLevelMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.faster_structure_location.ServerLevelMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.remove_spawn_chunks.ServerLevelMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.cache_strongholds.ServerLevelMixin,pl:mixin:APP:observable.common.json:ServerLevelMixin,pl:mixin:APP:lithium.mixins.json:alloc.chunk_random.ServerWorldMixin,pl:mixin:APP:lithium.mixins.json:chunk.entity_class_groups.ServerWorldAccessor,pl:mixin:APP:lithium.mixins.json:entity.inactive_navigations.ServerWorldMixin,pl:mixin:APP:lithium.mixins.json:profiler.ServerWorldMixin,pl:mixin:APP:lithium.mixins.json:util.entity_movement_tracking.ServerWorldAccessor,pl:mixin:APP:kubejs-common.mixins.json:ServerLevelMixin,pl:mixin:APP:adastra-common.mixins.json:common.ServerLevelMixin,pl:mixin:APP:adastra-common.mixins.json:common.multipart.ServerLevelMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:893) ~[client-1.20.1-20230612.114412-srg.jar%23292!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:814) ~[client-1.20.1-20230612.114412-srg.jar%23292!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:89) ~[client-1.20.1-20230612.114412-srg.jar%23292!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:modernfix-common.mixins.json:perf.thread_priorities.IntegratedServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:661) ~[client-1.20.1-20230612.114412-srg.jar%23292!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:251) ~[client-1.20.1-20230612.114412-srg.jar%23292!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at java.lang.Thread.run(Thread.java:1583) ~[?:?] {re:mixin}

-- Affected level --
Details:
	All players: 1 total; [ServerPlayer['jinqiu'/6780, l='ServerLevel[world]', x=126.98, y=144.69, z=-287.65]]
	Chunk stats: 4236
	Level dimension: minecraft:overworld
	Level spawn location: World: (8,85,-8), Section: (at 8,5,8 in 0,5,-1; chunk contains blocks 0,-64,-16 to 15,319,-1), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,-64,-512 to 511,319,-1)
	Level time: 13352696 game time, 13387436 day time
	Level name: world
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Level weather: Rain time: 14344 (now: true), thunder time: 87248 (now: false)
	Known server brands: forge
	Removed feature flags: 
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:893) ~[client-1.20.1-20230612.114412-srg.jar%23292!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:814) ~[client-1.20.1-20230612.114412-srg.jar%23292!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:89) ~[client-1.20.1-20230612.114412-srg.jar%23292!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:modernfix-common.mixins.json:perf.thread_priorities.IntegratedServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:661) ~[client-1.20.1-20230612.114412-srg.jar%23292!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:251) ~[client-1.20.1-20230612.114412-srg.jar%23292!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at java.lang.Thread.run(Thread.java:1583) ~[?:?] {re:mixin}
`

**Comment by joe1166** [comment]
经过我测试，怀疑是流体钻机抽干一个区块的流体后仍然尝试抽取，然后出现了某种错误
